### ISSUE TITLE
[Bug]: OpenSearch randomly refuses to start on GitHub Actions with absolutely no error logs

### ISSUE THREAD

**Issue by arg** [opensearch-project/opensearch-devops#100] opened 2022-12-21 14:02 UTC
### Describe the bug

In the CI workflow (GHA) we use OpenSearch 1.2.4. Sometimes it refuses to start. Also we can't even see any logs from it.

### To reproduce

Create a workflow with the following content:

```yml
name: ci

on:
  push:
    branches: [master]
  pull_request:


jobs:
  test:
    runs-on: ubuntu-latest

    services:
      opensearch:
         image: opensearchproject/opensearch:1.2.4 # we actually use our private custom image based on v1.2.4 where we just install mapper-murmur3 plugin
         ports:
           - "9200:9200"
         env:
           OPENSEARCH_JAVA_OPTS: "-Xms4096m -Xmx4096m"
           bootstrap.memory_lock: true
           discovery.type: "single-node"
           DISABLE_INSTALL_DEMO_CONFIG: true
           DISABLE_SECURITY_PLUGIN: true
           rootLogger.level: "DEBUG"
           logger.level: "DEBUG"
           logger._root: "DEBUG"
           logger.org.opensearch.index.reindex: "DEBUG"
           logger.org.opensearch.action: "DEBUG"
           logger.org.opensearch.action.admin.cluster.health: "DEBUG"
         options: >-
           --cap-add IPC_LOCK
           --ulimit nofile=65536:65536
           --ulimit memlock=-1:-1
           --restart always
    steps:
      # different sources suggest to tune system with sysctl for better OS stability
      - name: Configure environment
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      # this step should restart OpenSearch, wait for 20 seconds, then render OS container logs and check OS connectivity by making a request with curl
      - name: Restart OpenSearch
        run: |
          docker restart "${{ job.services.elastic.id }}"
          sleep 20
          docker logs "${{ job.services.elastic.id }}" 1>&2
          curl --output /dev/null --silent --head --fail 'http://localhost:9200'
      ...
```

### Expected behavior

OpenSearch service starts successfully.

### Host / Environment

GitHub Actions runner (Ubuntu 22.04)

### Additional context

As you may see in the "To reproduce" section, we added two extra GHA steps in attempt to fix OS service startup and also to at least be able to see some error logs. They didn't really help though: yes, in case of a normal successful startup we see nice debug logs (because of the increased verbosity) but when it refuses to start, we see nothing (see example log output below).

### Relevant log output

```shell
Run docker restart "e46b9cd3212fd41d3df13b3b6a4129bc4e90ab27e4fa998dd3f7d8b449b961df"
e46b9cd3212fd41d3df13b3b6a4129bc4e90ab27e4fa998dd3f7d8b449b961df
warning: ignoring JAVA_OPTS=-Xms4096m -Xmx4096m; pass JVM parameters via OPENSEARCH_JAVA_OPTS
Killing opensearch process 11                 <- killing OS by "docker restart"
Killing performance analyzer process 12
OpenSearch exited with code 143
Performance analyzer exited with code 143
[1]-  Terminated              "$@" "${opensearch_opts[@]}"
Killing opensearch process 10
Killing performance analyzer process 11
Error: Process completed with exit code 56.   <- curl reports error, OS is not running
```

**Comment by arg** [comment] 2023-01-02 15:24
@dblock thanks for your reply. We tried both suggestions, but unfortunately the issue still exists. Switching to GHA step (https://github.com/ankane/setup-opensearch) actually increased the chance of failure, no idea why. Also we added all the possible `sleep n` just to give OpenSearch more time to start.

For now we stick with the original strategy, the restart step helps to solve the situation when OS refuses to start initially, however there is always a small chance for OS to go down completely, resulting in a failed build.

Could it be an environmental or memory issue?

**Comment by prudhvigodithi** [comment] 2023-01-05 19:16
[Triage] Hey @arg can you try running the github workflow in debug mode, should give some logs there. Also can you try to disable the [PA component](https://github.com/opensearch-project/opensearch-build/tree/main/docker/release#disable-performance-analyzer-agent-cli-and-related-configurations) and run the cluster, I suspect the exit is happening because of memory (Xmx).

**Comment by jordarlu** [comment] 2023-02-14 19:09
Greetings, @arg, just wondering if you ever got a chance to try what @prudhvigodithi mentioned above? (on Jan 5th). If you haven't yet, please give it a shot. I once had an issue to bring up OpenSearch cluster abd later realized that I had memory issue on my EC2.. It might be the same situation to your case..  thanks!

**Comment by arg** [comment] 2023-02-15 11:01
@jordarlu @prudhvigodithi sorry for the late reply, re-running with debug mode on didn't bring much difference, there are absolutely no related logs in the output. I suspect the issue relates to memory consumption, since the standard GHA VMs are quite limited in resources. We ended up restructuring our GHA workflow in a way it minimizes the chance of a failed OpenSearch:

Services:

* Run OpenSearch as a service

Steps:

1. Tune VM (`sysctl` commands I listed above)
2. Restart OS service with `sysctl` changes applied
3. Check for OS connectivity
4. If OS is not accessible, restart it again

This workflow organization is not perfect: logically if OpenSearch runs fine before `sysctl` stuff, we don't really have to tune the system and restart the service. However it (almost) eliminates the chance of a broken OpenSearch. Very occasionally it still fails to run, even after two consequent restarts but with no logs we're not able to track down the root cause.

**Comment by jordarlu** [comment] 2023-02-15 17:13
Thanks for the prompt reply, @arg .. and happy to know and learn how you work around it to reduce the chances of the failure. It seems to be the MEM issue on GHA to me too as we couldn't reproduce it on EC2. 

I do want to update you with two more info that might be helpful in your case:
1. Via other issues/cases, the team remove the dependancy of the Performance Analizer (short for PA) and OpenSearch at  https://github.com/opensearch-project/opensearch-build/pull/287, If there is a possibility for you to try v1.3.7 or higher with PA disabling, that may be helpful on possible GHA MEM concerns 

2. You may also want to setup a Swap Space in Workflow as here https://github.com/pierotofy/set-swap-space 

thanks again and hope to hear more good news from you!!

**Comment by jordarlu** [comment] 2023-02-17 17:35
I am closing this issue for now, and please open a new issue/re-open it if you are still facing difficulties .. thank you!

**Closed by jordarlu** 2023-02-17 17:35 UTC
Labels: bug
