### ISSUE TITLE
config."opensearch.yml" value should be string type

### ISSUE THREAD

**Issue by smlx** [opensearch-project/opensearch-devops#30] opened 2021-08-09 13:36 UTC
Currently the default `values.yaml` uses a dict type for `config."opensearch.yml"`. Any custom values defined under this key are _merged_ with the default values. This means you need to carefully inspect the default values in order to know how custom values will be merged with this field and what the final applied values will be.

Instead if this field was a string type it would simply be replaced by any custom value instead of merged. This seems much safer and easier to use. It is also how `securityConfig.config.data.*` values work.

Any problem with me submitting a PR to fix this?

**Comment by TheAlgo** [comment] 2021-08-09 18:27
@smlx This was done purposely and kept as `dict` type to avoid mistakes while assigning values. @DandyDeveloper opinions?

**Comment by DandyDeveloper** [comment] 2021-08-10 00:39
@smlx This is intentional because we want the config to be read as a YAML to make it easier for all kinds of different reasons. 

For example, maybe you have a test cluster, so you could define an additional test values with some minor adjustments more indicative of your smaller cluster or some different self-signed certificates for transport comms. Rather than having multiple copes of the same config.

A number of CI/CD tools would also rely on YAML paths to find certain values which can be used for a number of additional benefits. You wouldn't be able to read or set specific fields in the `helm upgrade` command as well, without defining the entire config. 

Its consistent with how all other values are managed in helm. 

I actually think the default in the `values.yaml` can be removed entirely because AFAIK its just a dupe of the config that is already baked into the OpenSearch image. 

I do understand the justification for the other end of this. You'll probably find arguments on both sides for one or the other. My preference is to keep it how things currently are, but I'm just one voice.

**Comment by smlx** [comment] 2021-08-11 02:22
Thanks for the explanations. So are you saying that those default values align with the configuration baked into the images already? In other words, should you be manually overriding each of those specific configuration options anyway for a production deployment, even if they weren't set in the chart's default `values.yaml`?

**Comment by DandyDeveloper** [comment] 2021-08-11 03:01
@smlx If I remember correctly, the demo opensearch.yml baked into the image is basically the exact same as what we include in the values.yaml.

So IMO we can remove this entirely / comment it out. 

But yes, to me, all those available option should be replaced by your own input anyway, because those demo certs are available publicly. That CAN put your cluster at risk in transport/http. Those are most of the lines in that config. 

The rest:

```sh
        audit.type: internal_opensearch
        enable_snapshot_restore_privilege: true
        check_snapshot_restore_write_privileges: true
        restapi:
          roles_enabled: ["all_access", "security_rest_api_access"]
        system_indices:
          enabled: true
          indices: [".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state", ".opendistro-reports-*", ".opendistro-notifications-*", ".opendistro-notebooks", ".opendistro-asynchronous-search-response*"]
 ```

IMO are effectively mandatory anyway, except maybe `enable_snapshot_restore_privilege` and `check_snapshot_restore_write_privileges` which can just be disabled by a user easily through their own values.

**Comment by TheAlgo** [comment] 2021-08-17 06:47
@smlx if you are okay with the answer can we close this?

**Comment by smlx** [comment] 2021-08-17 08:10
Hi, yes thanks please close this :+1:

**Closed** 2021-08-17 08:11 UTC
Labels: question
