### ISSUE TITLE
[Enhancement][nightly playground] custom the changes

### ISSUE THREAD

**Issue by Flyingliuhub** [opensearch-project/opensearch-devops#150] opened 2024-03-19 22:23 UTC
**Is your feature request related to a problem? Please describe.**
The latest version of Playground Nightly has been released. We would like to add some requirements to meet our current needs. 

**Describe the solution you'd like**

- The tarball can be built from any repo and any branch, which is currently required by a lot of teams for purposes such as demonstration, bug fixes, and quickly previewing the new changes. For example, the PR raised by internal team or external users may use a different repo and branch than the current one, and we need to build a tarball for cross-team feature work, which requires all the different repos/branches from each developer.
- We would like to seed data (multiple data sources) into the nightly playground as well.     
   - [Dashboards](https://playground.opensearch.org/app/dashboards#/view/1d72819f-4e25-427b-b666-5a3e4580fcc5?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-11-22T05:28:45.013Z',to:'2022-11-29T05:28:54.583Z'))&_a=(description:'Analyze%20mock%20global%20orders%20and%20revenue%20from%20Multiple%20Data%20Sources',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'%5BMultiple%20Data%20Sources%5D%20Global%20Revenue%20Dashboard',viewMode:view))
   - feature flag for multiple datasources. 
   - feature flag for hide local cluster.
   - feature flag for authentication type.
- All other team need the custom feature flag as well. 
   - Machine learning
   - Dashboard new homepage 
   - third party plugin

-  All other teams' seed data, such as observability, alerts, security analytics, reporting, anomaly detection, etc.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

cc: @seraphjiang

**Comment by seraphjiang** [comment] 2024-03-23 15:21
@bbarani @gaiksaya would you help to triage the issue. Let us know if need more clarification.

**Comment by gaiksaya** [comment] 2024-03-26 23:54
Hi @Flyingliuhub @seraphjiang ,

Thank you for creating the request. 

1. The nightly playground is only responsible for deploying an already built tarballs onto the cluster. This set up does not build anything opensearch or opensearch-dashboards distributions on the go. Regarding customized builds, I believe you can replicate the exact set up in your accounts for a customized tarball build by the user. However, for something that is deployed publicly, this set up will be using distributions from ci.opensearch.org by design. Let us know if you need more details.

2. >We would like to seed data (multiple data sources) into the nightly playground as well.

There are 2 ways we can proceed with this request. 
    a. Create a PR with the seed data to index to the cluster in this repository
    b. We can index it using a snapshot of the seed data if it exists.
    
3. >All other team need the custom feature flag as well.

We can add as many custom feature flags as we want. However, just to make things clear at this point we intend to only have 2 endpoints, one point to upcoming 2.x release and other one point to next major version which is 3.0.0

cc: @bbarani @rishabh6788

**Comment by gaiksaya** [comment] 2024-08-23 23:54
Closing this issue. Please see [README](https://github.com/opensearch-project/opensearch-devops/tree/main/nightly-playground#opensearch-nightly-playground) for other FAQs.
Thanks!

**Closed by gaiksaya** 2024-08-23 23:54 UTC
Labels: enhancement
